### ISSUE TITLE
Killswitch?

### ISSUE THREAD

**Issue by RogerBoom** [pia-foss/manual-connections#107]
If random disconnect or connection loss software just fails and closes leaving user connected through their private IP

**Comment by g00nix** [comment]
These scripts do not aim at providing extended support, as the applications do. KillSwitch is harder to provide than expected, because you have to test it on all supported distributions.

The moment we officially release KillSwitch as part of this script, people will expect it to completely shut down all internet if the tunnel goes down. In order to guarantee this behavior on all distributions, thorough testing must be done on all supported distributions, and any modification or release of this script must be postponed if there are any security concerns regarding the KillSwitch not working correctly. This is a process that the Desktop Applications go through, and this requires multiple dedicated developers and also dedicated QA engineers. Another important detail is that this repo is usually used by people that apply a lot of modifications to their systems (including the network interfaces and iptables), so the KillSwitch must be adapted to each setup.

If you desire to create a KillSwitch for the manual connections, please fork the repo and configure the KillSwitch to work for your setup (your favorite protocol, the distributions you use and your network setup). If you create a repo that looks ok, we can add it to the [3rd party section](https://github.com/pia-foss/manual-connections#3rd-party-repositories) in the readme.
