### ISSUE TITLE
Documentation of tokenisation policy / approach?

### ISSUE THREAD

**Issue by inspector71** [pia-foss/manual-connections#120]
Could it be a reasonable idea to document the tokenisation orientation / assumption that seems to be within this code and now - completely a surprise to me - apparently in effect on the server side?

A note or link to a PIA explanation in the readme and or comments would be (would have been) very handy.

Thanks for the effort behind these scripts. As much as such headless mode scripting support is reasonable to consider a standard, default provision from a VPN company, it is not necessarily so. Hence, appreciate it!

**Comment by g00nix** [comment]
> Could it be a reasonable idea to document the tokenisation orientation / assumption that seems to be within this code and now - completely a surprise to me - apparently in effect on the server side?

I think you are right. This should be covered actually by an audit, and we already started this process by getting the Android App [ioXt certificed](https://www.privateinternetaccess.com/blog/private-internet-access-android-app-ioxt-certified/).

There should also be a blog article giving more insight regarding the authentication process, however this will have to wait as we are planning to improve the authentication mechanism, so it would make more sense to release an official statement after the migration from the old to the new system. The URL of the API will probably change, and also the format of the response, so changes will also be applied to this repository at that point anyway. That will be a good opportunity to also improve the docs with a bit more insight.

Thank you for the ticket. I will give your request as an example when will discuss this internally. I will also add this to our internal ticketing platform as this has to be first approved internally before moving forward. I will however close this ticket, as the github community can not really help us with this request.

> A note or link to a PIA explanation in the readme and or comments would be (would have been) very handy.

I like the idea of comments in the code.

> Thanks for the effort behind these scripts. As much as such headless mode scripting support is reasonable to consider a standard, default provision from a VPN company, it is not necessarily so. Hence, appreciate it!

Thank you! We are planning to improve this and add support for more platforms.

**Comment by inspector71** [comment]
Why closed? Could be left open as a reminder?

**Comment by g00nix** [comment]
> Why closed?

We have an internal ticketing system where we already keep track of this request, and this repository is being used too much for stuff that should normally go through [helpdesk](https://www.privateinternetaccess.com/helpdesk/new-ticket). This request doesn't have so much to do with the functionality of the source code within this repository, but more with the concept behind server-side auth mechanisms, which should actually be detailed in a blog post, not here.

Tokens are used in all the PIA apps and all the apps are actually open source, but this repo is a lot easier to read and to understand (since it's just a bunch of bash scripts) so somehow a lot of requests regarding server-side issues end up here.

**Comment by inspector71** [comment]
Fair enough. Thanks for the excellent explanation :)
