### ISSUE TITLE
`This script will need to remain active to use port forwarding, and will refresh every 15 minutes.`

### ISSUE THREAD

**Issue by bassamanator** [pia-foss/manual-connections#154]
After I ran this script, it ended with the following:
```
--> The port is XXXXX and it will expire on 2022-06-20T16:05:24.632145116Z. <--

Trying to bind the port... OK!
Forwarded port	XXXXX
Refreshed on	Tue Apr 19 00:37:06 EDT 2022
Expires on	Mon Jun 20 12:05:24 EDT 2022

This script will need to remain active to use port forwarding, and will refresh every 15 minutes.
```
But I had to close the terminal window.

My question is, how do I let the 'script' continue to run, or is it even necessary?

Thanks!

**Comment by triffid** [comment]
Run it under `gnu screen` or `tmux`, or set a cron job to rerun it periodically, or write a systemd service with a 15 minute timeout on restart.

**Comment by bassamanator** [comment]
@triffid I've very familiar with `screen`. Can I just run the script in `screen` and then detach the `screen`? Will that allow the script to run as it's supposed to? Thanks!

**Comment by triffid** [comment]
How/why *wouldn't* it work?

That's the *whole point* of terminal multiplexers like `screen` and `tmux` :P

**Comment by nbanb** [comment]
Dear all

I used to run this script in a detach screen, it work perfectly. 
The only thing (if you want to be "clean") is to modify the script(s) connect_to_{wireguard,openvpn}_with_token.sh and to add at line ~65 : 
check_tool screen

Kind regards,
nbanba

**Comment by bassamanator** [comment]
@nbanb Well, the check_tool function simply checks to see if a command is installed. I just don't see how making the script check to see if `screen` is install, is useful?

**Comment by nbanb** [comment]
@bassamanator 
For me, if you add (for your need) an external tool like screen or whatever to the solution, if you launch the PF script in a screen and screen is not installed, it will result in a failure. 
I rewrite parts of this project to make it run in parallele on the same machine but in differents linux network namespaces (for use as a multi-head / multi-destination vpn, (if you are interrested, it's availiable on github))  and I was required to add external tools like 'dnsmasq' to relay external DNS request to the container (and internal requests to the internal DNS server), 'microsocks' ... 
Trust me, when you use external tools, you need to check on the machine if they are installed otherwise it will result in a failure.   

All PR or merged of this project should be usable by someone who 'git clone' this project, so  for me, if the code need to use an external tool, it's required to check if it's installed

Kind regards,
nbanba

**Comment by bassamanator** [comment]
@nbanb I get what you're saying. Thanks for the explanation! :)
