### ISSUE TITLE
curl: (51) SSL: certificate subject name 'montreal402' does not match target host name 'montreal404'

### ISSUE THREAD

**Issue by Wingjam** [pia-foss/manual-connections#31]
When executing `./get_region_and_token.sh`, the best server hostname output is `montreal404`, but (I think) it should be updated to `montreal402` because when executing `PF_GATEWAY="xxx" PF_HOSTNAME="montreal404" PIA_TOKEN="xxx" ./port_forwarding.sh` without `-s` in the curl command when getting the new signature (step 1), it outputs the following error: 

```bash
curl: (51) SSL: certificate subject name 'montreal402' does not match target host name 'montreal404'
````

Changing `montreal404` to `montreal402` when calling the port_forwarding script fixed it!

**Comment by g00nix** [comment]
@Wingjam The result your are getting from the server list will always be different, because it gives you the best server at that specific moment in time. The results are not hardcoded. You got that specific SSL error because via VPN to `montreal402`, but forced the PF API certificate to contain `montreal404`, which is not possible.

The best way to avoid such situations is to chain the scripts. `./get_region_and_token.sh` allows you to specify `PIA_PF=true`, which will trigger the PF script after connecting to the VPN. This operation will pass the correct hostname through all scripts, which will guarantee that the PF script will not fail on SSL verification.

If you want to play with the scripts and execute them separately, you can also run `curl` with `-k`, since your connection to the PF API is already isolated by VPN and firewall. This is not something we do in the official scripts because it would just look bad, but when playing around with the scripts, this would be the easiest way to get PF running. Just don't run with `-k` when calling the WireGuard API on port 1337, as that goes through normal internet and should be properly protected by SSL.

**Comment by Wingjam** [comment]
@g00nix Thanks for your quick and detailed response! Yeah I was playing with the scripts separately because im running those inside my Synology NAS which is already connected to PIA via an OpenVPN config. The only thing missing is the port forwarding part. 

I think im gonna try to chain those scripts like you recommend and hope it doesn't break anything in the Synology OpenVPN configs!

**Comment by steff2632** [comment]
Im trying to do the same as you @Wingjam did chaining work?

im currently trying to chain them manually but not sure how to get the hostname properly.

**Comment by g00nix** [comment]
@steff2632 How do you connect to the server if you do not have the hostname?

**Comment by steff2632** [comment]
I connect through the ovpn files provided however after pulling `https://serverlist.piaservers.net/vpninfo/servers/v4` the hostname I think is different to uk-manchester.privacy.network and has a number added to the end. I think there needs to be a url to call that gives you're current hostname

**Comment by g00nix** [comment]
@steff2632 connecting via `uk-manchester.privacy.network` will get the best servers from DNS, and Load Balancing via DNS is not as precise as the serverlist. The serverlist will give you the best servers at that specific moment, but DNS will have some delays.
The automation in this repo describes how to connect by using the serverlist, as that is the preferred method of using the service.

If you still want to connect by using the DNS Load Balancer, please try to access the PF-API by enforcing `uk-manchester.privacy.network` as a hostname, like this:
```
  payload_and_signature="$(curl -s -m 5 \
    --connect-to "uk-manchester.privacy.network::$PF_GATEWAY:" \
    -G --data-urlencode "token=${PIA_TOKEN}" \
    "https://uk-manchester.privacy.network:19999/getSignature")"
```
The connection to the PF API is also encrypted via VPN and protected with firewall, so there is no risk if you actually run it with `curl -k`.

**Comment by Wingjam** [comment]
@steff2632 Unfortunately chaining does not work for me with Synology. The chaining stopped working in script `connect_to_openvpn_with_token.sh` when `Trying to start the OpenVPN connection...` (L: 165). I think its because we are running openvpn as a daemon in the script (and Synology don't love it). Will investigate this week if I got some spare time!

**Comment by steff2632** [comment]
I ended up editing them heavily because I'm using the Synology GUI to establish the OpenVPN connection.

Got all the way to binding the port but the server keeps rejecting it based on the signature. Stuck now because the signature returned is the signature that is sent.
[get_token.txt](https://github.com/pia-foss/manual-connections/files/5475523/get_token.txt)
[port_forwarding.txt](https://github.com/pia-foss/manual-connections/files/5475524/port_forwarding.txt)

attached are my edited files and I start them with this command

`PIA_USER={user} PIA_PASS={pass}PIA_PF=true PIA_AUTOCONNECT=manual ./get_token.sh`

any ideas @g00nix would be appreciated. Changed some of the curl commands because I think curl on synology doesn't have all the options

**Comment by g00nix** [comment]
@steff2632 you should create a fork or a new project on github so that we can properly inspect the code.

I think you are on a good path, though. Here are the steps you need to enable PF when already connected:
1. get a token from the meta API located at 10.0.0.1 on port 443
2. contact your gateway (the virtual IP of the OpenVPN server) on port 19999 to get payload/signature
3. use payload/signature to bind port
4. repeat step 3 every 15 minutes to keep port active

Once you have a payload/signature I suggest keeping it for 2 months till it expires.

We will probably get to this in the next weeks and officially release it, but it would make me really happy to see you get it working on your own.

**Comment by g00nix** [comment]
I opened a new ticket that covers the real issue here: #35
