### ISSUE TITLE
support for directly connecting to a specific server

### ISSUE THREAD

**Issue by dom11990** [pia-foss/manual-connections#36]
I would like to use openvpn (as I have in the past) and I have IP tables set so that only traffic on the tunnel adapter or udp port 1197 is allowed out or in. This worked fine before when I used a specific openvpn conf file. However, for some reason I now get TLS timeouts with that method, which is why I'm switching to these new recommended scripts. 

It is not clear to me, how I can cover my use case using the scripts. My understanding is that I would need to run get region to get a token every 24h (if my connection goes down). This would require me to alter my iptables which I would rather leave as is. Is there any (supported) way to connect directly to a specific server using only port 1197?

**Comment by g00nix** [comment]
@dom11990 There are multiple ways to obtain the IP:
1. getting it with `grep "remote " /opt/piavpn-manual/pia.ovpn`
2. getting it when you [get the region](https://github.com/pia-foss/manual-connections/blob/master/get_region_and_token.sh#L136)
3. getting it from the [OpenVPN script](https://github.com/pia-foss/manual-connections/blob/master/connect_to_openvpn_with_token.sh#L78) as it will not start without having the server IP in `$OVPN_SERVER_IP`

Hardcoding one IP can cause some random behavior because the server might go down due to hardware issues, or we might have to remove the IP from the fleet due to vendor issues. It's a lot better to adapt your setup based on the dynamic configuration that happens when the scripts get the best server.

You can however still hardcode this. Just let the scripts run, and modify `/opt/piavpn-manual/credentials` with your normal PIA username&password, and never run the script again so that it doesn't get overwritten. After that, OpenVPN will always connect to the IP on the last line in `/opt/piavpn-manual/pia.ovpn`, when you run this config.

We didn't eliminate the traditional authentication with the NextGen network, we just created new automation and new authentication systems that will offer better service quality and improved security. The serverlist will always give you the best IPs for that specific region and the new tokens offer faster authentication and improved security. However you can still use the service as you used to.

**Comment by iPherian** [comment]
@dom11990 Also if you needed a token for some other reason, you could get an up-to-date meta server by hardcoding the ip for the serverlist url, like I did: ( var PIA_SERVERLIST_HOST_IP -- [link](https://github.com/iPherian/manual-connections/commit/90427db76cd25d9960af843280fbb161ac4bc757#diff-44093944cfc327d70ffab5c108bbf3f6630db921528ccd98331b6b1b83d0b551R48-R51) and [link](https://github.com/iPherian/manual-connections/commit/90427db76cd25d9960af843280fbb161ac4bc757#diff-44093944cfc327d70ffab5c108bbf3f6630db921528ccd98331b6b1b83d0b551R84) )

Admittedly you'd still have to somewhat alter your firewall config, but it might be possible in a secure way. I suppose you could dynamically add ips to the firewall, or perhaps have a special user which can get through the firewall (iptables can allow based on uid). This user could have these scripts and their own copy of things like curl.

@g00nix would there be any problem with hardcoding the serverlist host ip you think? ( serverlist.piaservers.net )

**Comment by g00nix** [comment]
> @g00nix would there be any problem with hardcoding the serverlist host ip you think? ( serverlist.piaservers.net )

We had to change the IPs behind that domain in order to improve performance and they will probably change in the future too.

**Comment by iPherian** [comment]
Drat. Well, thanks for the info.

**Comment by g00nix** [comment]
@dom11990 @iPherian Do you need any more information on this topic, or can this ticket be closed?

**Comment by iPherian** [comment]
@goonix closing is good with me.

**Comment by dom11990** [comment]
Unfortunately, I don't quite "get it" yet. How can these scripts be used to _easily_ automate connecting to the VPN? It seems to me that there are numerous environment variables that need to be set and passed from one script to another to make it work. There is no over-arching script that handles all of this for you, correct? I've had to write scripts around these ones to make it work. Maybe I don't understand how the scripts work exactly (for example, what does run_setup actually do?), and of course I could dig into them, but it would be nice if the documentation was expanded a little bit to explain what the purpose of each is. 

I think everything is here to cover my use case, but it would require a bit of work to set up a systemd service to manage all this. Mainly because I don't like using bash scripts directly and need to brush up on syntax. Perhaps including a sample service to handle this process would be helpful?

Say I went for this approach: 

1. take the /opt/piavpn-manual/pia.ovpn file and link it to /etc/openvpn/pia.conf 
2. replace the remote with one I got from get_region_and_token.sh UDP
3. reaplce the auth-user-pass entry in the pia.conf file with a file to my plaintext login credentials
4. use systemctl start openvpn@pia to connect

This all works, but now, how can I enable port forwarding? 

Also, what is this excerpt referring to? "Call /bindPort every 15 minutes, or the port will be deleted!"

**Comment by iPherian** [comment]
@dom11990 As far as I understand it, to port forward, you need to get a token from the meta server, and then...

> Also, what is this excerpt referring to? "Call /bindPort every 15 minutes, or the port will be deleted!"

...a url called /bindPort must be retrieved every 15 minutes from the vpn endpoint to keep the port open. The vpn will close the port if more than that time goes by without such a request.

As you are already connected to the vpn, what would really be nice is a way to get a token as a separate independent script, and so here is a script: [get_token.sh](https://github.com/iPherian/manual-connections/blob/feature-independent-get-token/get_token.sh). And then you can run the following to get port forwarding:

(replace hostname in both places with real value and also user and pass)

```bash
token="$(PIA_SERVER_META_HOSTNAME=hostname \
  PIA_SERVER_META_IP=10.0.0.1 \
  PIA_USER=p1234567 \
  PIA_PASS=xxxxxxx \
  ./get_token.sh)"
PIA_TOKEN=$token \
  PF_GATEWAY="$( cat /opt/piavpn-manual/route_info )" \
  PF_HOSTNAME="hostname" \
  ./port_forwarding.sh
```

- You can get the hostname from the output of get_region_and_token.sh. It tends to look like "malta35" etc.

- Make sure you're using the repo's openvpn_up.sh script because that puts the needed gateway into the file.

- These all use vpn local ips so you shouldn't have to modify your iptables at all.

**Comment by iPherian** [comment]
@dom11990 And this is a modified form of a systemd service i've been using myself, it's short cuz the defaults work well with these scripts.

To use:

- put the commands mentioned above into a file called systemd_launcher.sh with this repo's files

- change $INSTALL_LOCATION to where you put this repo

```piavpn-manual.service```

```
[Unit]
Description=PIA vpn
Requires=network-online.target openvpn@pia.service
After=network-online.target openvpn@pia.service

[Service]
Type=simple
WorkingDirectory=$INSTALL_LOCATION
ExecStart=$INSTALL_LOCATION/systemd_launcher.sh
TimeoutStartSec=180
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
```

**Comment by iPherian** [comment]
@dom11990 

> Maybe I don't understand how the scripts work exactly (for example, what does run_setup actually do?)

run_setup just asks the user for what settings they want<sup>1</sup> (user, pass, protocol, etc) and then runs the actual behavior script of get_region_and_token.sh with the corresponding environment variables.

1. Well it also disables ipv6 but you can do that yourself

**Comment by iPherian** [comment]
@g00nix can feel free to correct me of course

**Comment by g00nix** [comment]
> How can these scripts be used to easily automate connecting to the VPN?

In order to connect to the VPN, here is a one-liner that will allow you to start a VPN connection with WireGuard and Port Forwarding (if the closes region supports it):

```
PIA_PF=true PIA_AUTOCONNECT=wireguard PIA_USER=p0123456 PIA_PASS=xxxxxxxx ./get_region_and_token.sh
```

If you wish to fully automate this when your system boots, you will have to choose an init system, or start the scripts via a container service. This is a list of popular init systems:

- OpenRC
- runit
- s6
- SysVinit
- systemd

Here is a list of init systemd rated an online voting system: https://www.slant.co/topics/4663/~linux-init-systems

Here is also a list of popular container managers that could be used to start a container at boot to modify your network settings:

- docker
- podman
- LXC
- LXD

The easiest way to move forward would be to use the init system that your favorite operating system uses to call `./get_region_and_token.sh` with the setting you wish for your connection. 

> It seems to me that there are numerous environment variables that need to be set and passed from one script to another to make it work.

Considering people will want to use the scripts for different protocols, we need to provide a way for people to change the behavior of the scripts according to their preferences.

Environment variables are the current best practice for configuring scripts. You will see most micro-services, docker images and modern scripts change their behavior via environment variables. This is way all cloud platforms (ex: AWS, GCP, Azure) allow you to inject env vars into containers, VMs and functions in order to tailor the behavior to your requirement.

As a lot of people will use these scripts in different scenarios (different distributions, different operating systems, container environments etc), we need to provide a modern and generally accepted for people to choose between protocols. The only real alternative would be to load the settings from a file, and you can do that anyway by sourcing an env file with bash. Environment Variables are fully compatible with any automation the users will choose for their systems.

> There is no over-arching script that handles all of this for you, correct? I've had to write scripts around these ones to make it work.

Because each user can configure his own machine the way he wants it to be configured, it's impossible to create one script that covers everything. We are currently working to expand this repository with support for multiple distributions and more scenarios. There already are a lot of 3rd party repositories that offer solutions for specific platforms.

> Maybe I don't understand how the scripts work exactly (for example, what does run_setup actually do?), and of course I could dig into them, but it would be nice if the documentation was expanded a little bit to explain what the purpose of each is.

`run_setup.sh` will guide you through setting up a VPN connection. This script has been designed to offer a simple solution for people that do not have time to go through the scripts. `run_setup.sh` should work in most scenarios.

I am sorry if the README, the comments within the scripts and the log messages do not provide enough information regarding the behavior of the scripts. Please let us know which area of the scripts is not documented enough and we will do our best to improve the documentation.

> I think everything is here to cover my use case, but it would require a bit of work to set up a systemd service to manage all this. 

If your distribution uses `systemd` and you wish to start the scripts on boot, then creating a [systemd unit](https://wiki.archlinux.org/index.php/Systemd#Using_units) would help in this direction. If you want to fully automate the setup, you should also test possibilities of setting up a KillSwitch for your network configuration.

> Mainly because I don't like using bash scripts directly and need to brush up on syntax.

We have to make the scripts accessible for everybody, and `bash` is the most accessible way to provide support for most setups. We tried to add as many comments as possible and to keep the bash syntax as simple as possible so that the scripts are very easy to read. There are users that already implemented the same functionality with GoLang and Python, however moving officially into that direction to support manual setups would make the setup very difficult for the majority of users.

The easiest way to setup your system is by using the official PIA Desktop App, as it provides the following features:
- can start on boot
- has a kill switch
- protects against leaks on every supported distribution
- allows split tunneling
- allows you to save your favorite region.

Providing all of these features is out of the scope of this repo.

> Perhaps including a sample service to handle this process would be helpful?

This is a good idea, however we will have to add a disclaimer. People should not expect an init script to actually protect against leaks or to have a kill switch. Adding this level of automation might also create the expectation among users that the script will also offer full protection, which is impossible in the case of manual configuration, where the user can modify the behavior of his network. For full protection and easy setup, the best way to move forward is to use the official PIA App.

**Comment by g00nix** [comment]
@dom11990 we can also talk on IRC (server: freenode; channel: #privateinternetaccess; nick: gunix) or on Telegram: https://t.me/gunix

Maybe we can figure the best setup for your system.

**Comment by iPherian** [comment]
> ...a script: [get_token.sh](https://github.com/iPherian/manual-connections/blob/feature-independent-get-token/get_token.sh).
>
> ...
>
> ```shell
> token="$(PIA_SERVER_META_HOSTNAME=hostname \
>   PIA_SERVER_META_IP=10.0.0.1 \
>   PIA_USER=p1234567 \
>   PIA_PASS=xxxxxxx \
>   ./get_token.sh)"
> PIA_TOKEN="$token" \
>   PF_GATEWAY="$( cat /opt/piavpn-manual/route_info )" \
>   PF_HOSTNAME="hostname" \
>   ./port_forwarding.sh
> ```

@dom11990 Oh and I should mention:

- this doesn't require any additional iptables config, as it uses internal VPN ips (does require already being connected though).

- the get_token script should be compatible with most setups, as it is based on this repo's latest master and has only minimal changes to achieve it's purpose.

**Comment by dom11990** [comment]
First off, thank you for your detailed responses. My solution had also been to extract the token request section of the scripts into a separate entity. While I like this concept, I would really like to see a PIA supported way of doing this, it seems like what @iPherian made will do the job, what about making a PR for this? Whenever you go off the main road (in this case the PIA app) it is important to at least stick to supported API so that things don't change behind the scenes without you knowing. 

> PIA_PF=true PIA_AUTOCONNECT=wireguard PIA_USER=p0123456 PIA_PASS=xxxxxxxx ./get_region_and_token.sh
This brings me back to my original question of how to connect to a specific server using only the provided scripts. I think now the answer to this is "not possible without modification". 

@g00nix Yes, unfortunately, this doesn't work in my setup. I pasted my iptables below which I think will make it clear why. Before I establish a connection to the VPN, only traffic on port 1197 is allowed (also local). All other network traffic is dropped so the get_region_and_token.sh script times out. 




> This is a good idea, however we will have to add a disclaimer. People should not expect an init script to actually protect against leaks or to have a kill switch. Adding this level of automation might also create the expectation among users that the script will also offer full protection, which is impossible in the case of manual configuration, where the user can modify the behavior of his network. For full protection and easy setup, the best way to move forward is to use the official PIA App.

I agree that going the manual route opens you up for security flaws. It would be great if PIA could provide some knowledge base articles that explain the common causes of leaks, and maybe how to test / protect yourself from them. It seems the only articles you find on the internet are blog posts from random people. PIA can flaunt their expertise a bit here and educate their users :)

> I am sorry if the README, the comments within the scripts and the log messages do not provide enough information regarding the behavior of the scripts. Please let us know which area of the scripts is not documented enough and we will do our best to improve the documentation.

I think the information about the environment variables is very helpful, though perhaps incomplete. What would also be nice is an explanation of what each script does so that the user has an immediate understanding of what elements of the scripts are volatile and which are not as well as which scripts can be called when. I, for example, thought I run run_setup once, and then can simply up and down the VPN and it would pull the configuration from what my execution of run_setup created. This is not the case however, because all run_setup does is configure some variables, it is therefore completely volatile (between shells). An explanation of the token would be nice too. Seems to only be needed for PF?

A quick example: If I call run_setup.sh, I can set if I want to use PIA_DNS, let's say I do. Then the script calls get_region_and_token.sh to retrieve the IPs and the token, and lastly it calls connect_to_openvpn_with_token. In this last script, the PIA_DNS variable alters the behavior of the script (which is not in the documentation as an optional environment variable btw). So if I run this script in isolation, I need to have this variable. I became somewhat unwary because now I don't know what else I need since this one wasn't mentioned in the documentation haha.

Now I know this is in early stages so I'm not expecting a tried and true solution. I don't mean to sound upset or entitled (as I am neither) I simply wish to convey my use case and see if you think it warrants expanding this repo to support it.

My idea would be as follows:
1. Split get_region and get_token into separate scripts. 
2. Remove the need for a token when connecting to the VPN (it's not necessary as far as I can tell unless you need port forwarding)
3. run_setup calls get_region (instead of get_region_and_token) and at the end print the commands to connect to the vpn (it does this already, but perhaps double check to ensure all the environment vars are represented that are needed, eg. PIA_DNS)
4. connect_to_openvpn/wireguard only connects to the VPN, if PIA_PF is true it calls port_forwarding
5. port_forwarding gets it's own token to configure the port forward

I think this is a more intuitive encapsulation for the scripts and would cover a wider set of use cases. For example, I could use this out of the box with my iptable killswitch. What do you think?

On the topic of killswitches, would this not be a simple implementation?
```
dom:~ $ sudo iptables --list-rules
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i lo -j ACCEPT
-A INPUT -s LOCALSUBNET/24 -j ACCEPT
-A INPUT -p udp -m udp --sport 1197 -j ACCEPT
-A INPUT -i tun+ -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -d LOCALSUBNET/24 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1197 -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
```

Thanks for the discussion!

**Comment by iPherian** [comment]
@dom11990 

(1) I very much agree that get_token should be a seperate script. I've seen many people have to extract that behavior in order to get their own particular setup running (the act of getting a token is so fundamental to using PIA services). It would be nice and I think in line with the purpose of this repo if those without bash experience could run all of the building blocks seperately, and in whatever order they wished. (while keeping the default sequence in get_region_and_token for those who don't care).

(3) I do however think that there is a value in having a seperate entry point script (right now get_region_and_token) from the user-friendly wizard script (run_setup). Perhaps get_region_and_token could itself call get_region and get_token and all the others. 

  - side note: If indeed get_region_and_token is the entry point, perhaps it should be named differently. It's current name sounds more to me like a utility script than what it actually does right now: initiate the entire procedure.



@g00nix any thoughts? I could whip up a PR or two.

**Comment by iPherian** [comment]
PR #38

**Comment by g00nix** [comment]
Thank you for the recommendations and the very good ideas. Here is a quick update from my side on what has been discussed on this issue:

- We will release v2.0.0 that will have support to get a specific region, and it will have different scripts for get_region and get_token. I also mentioned this in the PR.
- Networking is a very complex specialization which usually takes decades to master. Networking on Linux is very well documented and the entire system is open source, so anybody can research and experiment. We do our best to provide the best security possible via the PIA Apps, however creating an extended documentation on Linux networking is better suited for other projects.
- You should use tokens, not user/pass, as the new token mechanism provides improve security. OpenVPN allows authentication with user/pass only because forbidding it will break a lot of legacy setups that a lot of users are still running.

**Comment by g00nix** [comment]
Please check https://github.com/pia-foss/manual-connections/pull/52

**Comment by g00nix** [comment]
Closing this as a duplicate of https://github.com/pia-foss/manual-connections/issues/20 so that it's easier to keep track of the development that is ongoing.
