### ISSUE TITLE
PowerShell version

### ISSUE THREAD

**Issue by shorbachuk** [pia-foss/manual-connections#56]
Is there a powershell version of these planned, would like to use these on windows.

**Comment by g00nix** [comment]
There are no plans internally but if somebody translates the scripts to PowerShell, we can add that to the [3rd Party section](https://github.com/pia-foss/manual-connections#3rd-party-repositories) in the README.

I suggest to leave this issue opened. If anybody wants to pick this up, please leave a comment here so that everybody is aware of the progress.

**Comment by ImjuzCY** [comment]
I've started to translate the scripts to Powershell. Other than port forwarding and openvpn, I have translated other scripts [here](https://github.com/ImjuzCY/pia-posh).

One thing is the cacert from this repo is being treated as untrusted by Windows' `curl.exe`. Do you know why is it the case? @g00nix

**Comment by g00nix** [comment]
Congrats on the great work. Looking awesome!

---
> One thing is the cacert from this repo is being treated as untrusted by Windows' `curl.exe`. Do you know why is it the case?

I am not a Windows user, but I suspect there is some issue with curl on Windows. `--cacert "ca.rsa.4096.crt"` should be all you need.

---

@ImjuzCY  When do you think your project will be ready to add to the readme of this repo?

**Comment by g00nix** [comment]
@ImjuzCY  I would also try [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1) and [Invoke-RestMethod](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1), since these are native for PowerShell and might be more elegant than using curl.

**Comment by ImjuzCY** [comment]
> @ImjuzCY I would also try [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1) and [Invoke-RestMethod](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1), since these are native for PowerShell and might be more elegant than using curl.

I was using `Invoke-RestMethod` but it doesn't support `--connect-to` option of `curl`, which is needed. So I resorted to `curl.exe`.

The scripts are structurally working already, I just need to clean up a bit before adding it to this repo. I'll let you know when it's ready

**Comment by ImjuzCY** [comment]
@g00nix I think you can add my repo to the README here since it's already functional

**Comment by g00nix** [comment]
> @g00nix I think you can add my repo to the README here since it's already functional

Yes. I will add it to the README and close the ticket.

**Comment by g00nix** [comment]
Added this to README in the [testing branch](https://github.com/pia-foss/manual-connections/tree/testing). It will get merge into master alongside multiple other modifications.
