### ISSUE TITLE
[Security/Wireguard] When is the server supposed to drop/"forget" a public key?

### ISSUE THREAD

**Issue by Slugger** [pia-foss/manual-connections#57]
I'm working on a management client for Linux.  Everything is working nicely, but I'm seeing some behaviour that I'm not so sure about.  Maybe I'm just not understanding the expected behaviour?

When I register a public key with a server the json response includes all the details needed to setup the wg interface (server's endpoint, port, vip, public key).  And that's great, it works, I can setup the interface from my end and send traffic thru it.  Now I run `wg-quick down pia0` to bring the interface down.  Definitely no more traffic going across this interface.  Many hours later (at least 4), I run `wg-quick up pia0` using the same conf file with the same keys from four+ hours ago.  Traffic starts flowing again immediately.  Is this expected?  I was under the impression that if the PIA side didn't see traffic from a given public key within a certain amount of time (minutes, I thought?) it would remove the public key from its side forcing me to register a new public key (or reregister my existing one) and create a new interface?  I thought this is why we _needed_ to use a persistent keepalive for all PIA wg interfaces?

If I'm not understanding things correctly, is there documentation explaining what is supposed to happen?  i.e. is a registered public key good forever (or at least until the PIA subscription ends)?

**Comment by g00nix** [comment]
The scripts generate a new random key on every new connection:
https://github.com/pia-foss/manual-connections/blob/master/connect_to_wireguard_with_token.sh#L70

The apps do the same. If you want to create a management client, please do the same thing: generate random keys for each connection.

There is no reason to delete the keys. They were supposed to be there for a long time for mobile clients so that the phone jumps back into the connection the moment you pick it up in the morning, but that works smooth enough by generating a new key when resuming from standby, so mobile clients don't require the servers to hold the key. There still is a requirement from manual connections that do not want to use keepalive for various reasons and have troubles preventing leaks when not using the VPN, and for those specific devices it's better if we keep the keys longer (we did have this request).

Even if that is the case, please do not base any automation on the idea that they keys will stay on the server for a long time, since the timeout might change in the future. The key will probably be there for half a day, but an "official documentation" means people will start basing automation on it and that is not the right way to move forward. If the connection seems dead, the best thing is to connect to a new server (by using a new random key).

There is no reason to keep this issue opened, but I am curious what you are creating. Can you share more information about your client?

**Comment by Slugger** [comment]
@g00nix I'm not planning to assume the keys are long lived, but rather I'm concerned about why the keys are so long lived?  If the keys are long lived then is the server also maintaining the endpoint address of that public key for that long as well?

My client monitors each interface periodically and once it detects traffic isn't flowing on an interface it destroys it, creates a new key pair, registers the public key and creates a new wg interface.  I was more wondering why public keys are kept valid on the server for so long after no traffic flows and what the ramifications of that might be?

As for my project, I'm creating a client for Linux that can maintain multiple wg connections on a single host simultaneously.  It will handle the typical single interface config as well, but such a config is better left to the official client.

This client will maintain multiple interfaces, presumably each connecting to a different geographical location, and the client will monitor the interfaces and optionally port forwarding on each interface.  The client detects when any interface is no longer responding, destroys it and recreates it with a new key pair.  Traffic can then be policy routed out any of the active connections as desired.  One connection might be for dealing with geolocking, another for day to day traffic and another for hosting a service (with port forwarding enabled), etc.  Basically this client is sitting on a Linux host acting as a router for all my pia wg vpn traffic.

**Comment by g00nix** [comment]
> I'm not planning to assume the keys are long lived, but rather I'm concerned about why the keys are so long lived? If the keys are long lived then is the server also maintaining the endpoint address of that public key for that long as well?

No, the public IP gets deleted after 3 minutes of inactivity. The servers are encrypted and services run only within the memory and we have SSH protection with firewall and DNSSEC/SSHFP so there is no chance for anybody to get in, but still, we have a daemon that deletes all public IPs for inactive connections. This is based on the fear that the apocalypse have might happen and somebody might actually get into a server and in that case it would be bad if they could see public IPs connected over the last hours. So are safe also in case of apocalypse. :smile: 

We can't generate random IPs for the users, but we can generate random WireGuard keys.


> As for my project, I'm creating a client for Linux that can maintain multiple wg connections on a single host simultaneously. It will handle the typical single interface config as well, but such a config is better left to the official client.

Sounds like a very nice project. I hope you are having fun developing it. Are you going for GoLang?

**Comment by Slugger** [comment]
It's funny you mention golang.  That was the plan, but by day I'm a Java engineer and so it was real quick and easy to whip up a working proof of concept in java.  I have that working and running on my system now.  But I also know that a java app is rather heavy for a router type system.  This project was supposed to be my reason to dive into golang but then I also needed something up and running asap so I went with java.  The _plan_ is to go back and do it again in golang, but we shall see.

**Comment by g00nix** [comment]
I mentioned GoLang cause there is a very good library for GoLang to control WireGuard interfaces. It can be found [here](https://github.com/WireGuard/wgctrl-go). That's what we use to offer everything I described above.

No idea about Java, though. I didn't touch Java in a long time.
