### ISSUE TITLE
iptables-restore v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

### ISSUE THREAD

**Issue by Chronigan** [pia-foss/manual-connections#65]
I get the following when I run setup.sh I have had it working before but for some reason after a reboot it stopped. I am running this on a Raspberry pi 4 with raspbian in server mode(no gui) if you need any specific log files let ,e know.

```
`Trying to connect to the PIA WireGuard API on 154.3.250.189...
{
    "status": "OK",
    "server_key": "GkagiPJGCQETk1xpCaXSQLMb1Zdh8DATrNXlN4gAMVE=",
    "server_port": 1337,
    "server_ip": "154.3.250.189",
    "server_vip": "10.46.128.1",
    "peer_ip": "10.46.252.202",
    "peer_pubkey": "fl1zxauK+/wNQ8ex9tH2MfYKok6bgxbBsf+FLIXDUhw=",
    "dns_servers": [
        "10.0.0.243",
        "10.0.0.242"
    ]
}

Trying to disable a PIA WG connection in case it exists...
wg-quick: `pia' is not a WireGuard interface

Trying to write /etc/wireguard/pia.conf... Trying to set up DNS to 10.0.0.243. In case you do not have resolvconf,
this operation will fail and you will not get a VPN. If you have issues,
start this script without PIA_DNS.
OK!

Trying to create the wireguard interface...
[#] ip link add pia type wireguard
[#] wg setconf pia /dev/fd/63
[#] ip -4 address add 10.46.252.202 dev pia
[#] ip link set mtu 1420 up dev pia
[#] resolvconf -a pia -m 0 -x
Too few arguments.
Too few arguments.
[#] wg set pia fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev pia table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
iptables-restore v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] resolvconf -d pia -f
Too few arguments.
Too few arguments.
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev pia
`
```

**Comment by g00nix** [comment]
This bug can originate from:

1. the WireGuard tool `wg-quick`, which is part of [wireguard-tools](https://github.com/WireGuard/wireguard-tools)
2. your system, as your install seems broken cause you seem to have conflicts between `nf_tabels` and `iptables`
3. official raspbian packages, as maybe they have old versions of packages or maybe they did not correctly add all dependencies.

Sadly neither of the possible causes means there is an issue with this repository, so I have to close the ticket. My instinct tells me that the problem is number 2, and that you research on how to resolve the conflict between iptables and nf_tables. If you search your error message on popular search engines, you will see that a lot of people have this issue on raspbian.

**Comment by Chronigan** [comment]
I was able to solve my issue by running the script here https://pivpn.io/ After I went through that setup I re-ran run_setup.sh and it was able to create the wire guard connection.
