### ISSUE TITLE
Issues with API

### ISSUE THREAD

**Issue by 3zzy** [pia-foss/manual-connections#82]
https://serverlist.piaservers.net/vpninfo/servers/v4 response ends with a random hash. I'm expecting it to be a JSON and want to parse it but the hash causes an error. Is that intentional?

Also, I can't seem to add the wg key, I keep getting:

```
{
    "status": "ERROR",
    "message": "Login failed!"
}

```

Although I'm pretty sure the token is correct as its generated seconds before. What am I doing wrong?

**Comment by g00nix** [comment]
Hello, @3zzy!

That is not a random hash, that is a signature. ^^

You can ignore it if you use HTTPS to get the SL. Just run
```
curl https://serverlist.piaservers.net/vpninfo/servers/v4 | head -1 | jq
```

Regarding the failed logins, I can not say what you are doing wrong as I don't see the code you are using. The code from this repository is however working correct, so I have to close this issue since there is no actual issue with the code on the repo.

Can you post the code that is causing a `Login failed!`?

**Comment by 3zzy** [comment]
@g00nix I'm just trying these in Postman. Here's my collection:

```
{
	"info": {
		"_postman_id": "ce1fafe9-d13a-411b-8cf4-99e32a3454d2",
		"name": "PIA",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Get Region",
			"event": [
				{
					"listen": "test",
					"script": {
						"exec": [
							"const jsonData = JSON.parse(responseBody.split('\\n')[0]);",
							"const region_in = jsonData.regions.filter((r) => r.country === pm.environment.get('COUNTRY'));",
							"const region_in_wg_hostnames = region_in.reduce((acc, r) => {",
							"\tvar hostnames = r.servers.wg.map((obj) => obj.ip);",
							"\tacc = acc.concat(hostnames);",
							"\treturn acc;",
							"}, []);",
							"",
							"const random_hostname = region_in_wg_hostnames[Math.floor(Math.random() * region_in_wg_hostnames.length)];",
							"pm.environment.set('WG_HOSTNAME', random_hostname);"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://serverlist.piaservers.net/vpninfo/servers/v4",
					"protocol": "https",
					"host": [
						"serverlist",
						"piaservers",
						"net"
					],
					"path": [
						"vpninfo",
						"servers",
						"v4"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Token",
			"event": [
				{
					"listen": "test",
					"script": {
						"exec": [
							"var jsonData = JSON.parse(responseBody);",
							"pm.environment.set(\"PIA_TOKEN\", jsonData.token)"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"auth": {
					"type": "basic",
					"basic": [
						{
							"key": "password",
							"value": "xxxxxxxxx",
							"type": "string"
						},
						{
							"key": "username",
							"value": "xxxxxxxxx",
							"type": "string"
						}
					]
				},
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://privateinternetaccess.com/gtoken/generateToken",
					"protocol": "https",
					"host": [
						"privateinternetaccess",
						"com"
					],
					"path": [
						"gtoken",
						"generateToken"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get WG",
			"protocolProfileBehavior": {
				"disableBodyPruning": true
			},
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "pt",
							"value": "$PIA_TOKEN",
							"type": "text"
						},
						{
							"key": "pubkey",
							"value": "$pubKey",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "https://{{WG_HOSTNAME}}:1337/addKey?pt={{PIA_TOKEN}}&pubkey={{PUB_KEY}}",
					"protocol": "https",
					"host": [
						"{{WG_HOSTNAME}}"
					],
					"port": "1337",
					"path": [
						"addKey"
					],
					"query": [
						{
							"key": "pt",
							"value": "{{PIA_TOKEN}}"
						},
						{
							"key": "pubkey",
							"value": "{{PUB_KEY}}"
						}
					]
				}
			},
			"response": []
		}
	]
}
```

So I'm trying to get a region, then token and then finally add the key but the last step doesn't work. Always says login failed although I'm quite sure the username password is the same I use everywhere.

**Comment by 3zzy** [comment]
@g00nix Sorry for being dumb but whats the purpose of the signature? Wondering cause it fails to parse if I expect a json response and try to parse it directly using `JSON.parse(respondeBody)` 

Is this a common standard to have a signature appended or just something you do?

**Comment by g00nix** [comment]
Regarding the reason you get `Login failed` on WireGuard: you are querying the WG API with your username and your password, instead of the token. [Here](https://github.com/pia-foss/manual-connections/blob/338ca1ac4297abd41ba315097a458e1a27d866d1/connect_to_wireguard_with_token.sh#L85) is an example of how a correct request looks. The tokens offer increased security, so when we released the new WireGuard protocol we didn't provide support for username/password authentication, as we want to encourage people to use tokens. Username/Password authentication is still offered for OpenVPN to enable support for legacy devices that didn't migrate yet to the new solution.

Regarding the signature: a lot of users can not get the server list because their internet connection is restricted, so they are forced to get the server list from other sources. The signature gives the users a guarantee that the server list came indeed from PIA and wasn't altered in the process. This is not "standard", it's something we have to do as we are providing a privacy service.

**Comment by 3zzy** [comment]
@g00nix Thanks for the prompt response.

I'm pretty sure I'm not using username/password but just to be double sure I hardcoded the values instead of using variables and still got the same error:

https://45.120.139.133:1337/addKey?pt=+3GF4Fw+qT9b_CATZ5B055FLoMBF_E5Sn9UiOL8TMw4arJfsdRbDFZSYrl1w6jdnMvcMi07owvXrAGwYj7M2CKbU9xk4kloWIBpF60SVpeBuBYLE3x6ZAC5ld8A=&pubkey=hMWpqb3FEATHIbImPVWB/5z2nWIXghwpnJjevPY+1H0=

.. btw this token was generated seconds ago. 

Thanks for the explanation about the signature. I understand the reason but still a JSON response is not valid JSON bothers me a little but I got around it by just doing `JSON.parse(responseBody.split('\n')[0])`

**Comment by g00nix** [comment]
Please do not post tokens on any public forum. :smile: 

Since you are using the token, I don't know why this is not working. Are you sure the URL is encoded?

**Comment by 3zzy** [comment]
<img width="952" alt="Screen Shot 2021-01-16 at 1 50 03 pm" src="https://user-images.githubusercontent.com/105034/104795374-e3809b00-5801-11eb-9090-7296c62786c7.png">

**Comment by g00nix** [comment]
I have now idea how you can do this, but please completely remove that picture from the internet, as you can still most of the token under the black line. :-D

Please, let's take this to a private discussion. You can find me on Telegram at https://t.me/gunix or on IRC on Freenode with the nick gunix.
