### ISSUE TITLE
more information is required in the log message of PF

### ISSUE THREAD

**Issue by bassamanator** [pia-foss/manual-connections#86]
My installation got stuck at the very end on my Raspberry Pi 4-8gb. I had to ctrl+z to get out of it.
Settings:
-pf=true
-wireguard
-pick your own server
-force PIA dns=no

Tried it a second time and same thing, gets stuck at the end though I *think* it creates the new PIA wireguard connection.
```
Trying to bind the port... OK!
Forwarded port	28659
Refreshed on	Tue Jan 26 00:57:44 EST 2021
Expires on	Mon Mar 29 13:46:29 EDT 2021
l
^Z
[1]  + 17583 suspended  sudo ./run_setup.sh
```

**Comment by g00nix** [comment]
Your device is already connected (scroll up to see the log). [Port forwarding](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh) needs to get refreshed every 15 minutes (as described in the comments in the script). I will add another echo to the log so that it is clear why the script has to keep running for PF to work.

**Comment by g00nix** [comment]
Fixed via https://github.com/pia-foss/manual-connections/pull/88
